export type User = {id:string;username:string;admin:boolean;csrf_token:string};
export type Metric = {value:string|null;status:string;reason:string|null;input_fact_ids:string[];display_value:string};
export type Project = {id:string;name:string;revision:number;metrics:Record<string,Metric>;metrics_current:boolean;section_current:boolean;production_template_status:string;members?:{user_id:string;username:string;role:string}[]};
export type Doc = {id:string;name:string;sha256:string;model_allowed:boolean;parse_state:string};
export type FinancialItem = {supplemental?:boolean;id:string;concept:string;source_name:string;raw_value:string;raw_unit:string;normalized_value:string|null;source_text:string;source_start_line:number;source_end_line:number;status:string;evidence?:Record<string,unknown>;confirmation_reason:string|null;source_order?:number;source_section?:string;source_label?:string;source_cells?:string[];source_headers?:string[]};
export type StatementCheck={code:string;status:'passed'|'conflict'|'not_checked_missing_disclosure'|'not_checked_unverified_source';difference:string|null;tolerance:string|null;missing_concepts:string[];involved_concepts:string[];item_ids?:string[]};
export type FinancialStatement = {id:string;run_id?:string|null;document_id:string;statement_type:'balance_sheet'|'income_statement'|'cash_flow_statement';entity:string;scope:string;period:string;period_normalized:string|null;period_kind:string|null;currency:string;raw_unit:string;unit_scale:string|null;state:string;issues:string[];items:FinancialItem[];source_status?:'consistent'|'needs_review'|'not_available';source_issues?:string[];formula_status?:'passed'|'warning'|'not_checked'|'mixed';checks?:StatementCheck[];semantic_review_count?:number;manual_review_required?:boolean};
export type Segment = {type:'text'|'metric';text?:string;ref?:string};
export type Draft = {section_id:string;title:string;input_hash:string;question_answers:{question_id:string;status:string;block_ids:string[]}[];blocks:{block_id:string;segments:Segment[]}[];table_id:string;synthetic:boolean};
export type Section = {version:number;draft:Draft|null;current:boolean;input_hash:string};
export type Task = {id:string;kind:string;mode:string;state:string;attempts:number;reason:string|null;quality_state:string;review_state:string;result:{export_id?:string;document_id?:string;statement_count?:number;item_count?:number;pipeline_version?:string;manifest?:{quality_state?:string;counts?:Record<string,number>;issues?:string[]};extraction_status?:string;model_allowed?:boolean;coverage?:{method:string;tables_found:number;tables_parsed:number;numeric_cells:number;extracted_cells:number;blank_cells:number;unreadable_cells:number;status:string}|null}};
let csrf='';
export function setCsrf(value:string){csrf=value}
export async function api<T>(path:string,method='GET',data?:unknown):Promise<T>{
 const form=data instanceof FormData;
 const response=await fetch('/api'+path,{method,credentials:'same-origin',headers:{...(method!=='GET'?{'X-CSRF-Token':csrf}:{}),...(!form&&data!==undefined?{'Content-Type':'application/json'}:{})},body:data===undefined?undefined:form?data:JSON.stringify(data)});
 if(!response.ok){const payload=await response.json().catch(()=>({detail:'request_failed'}));const detail=payload.detail;throw new Error(typeof detail==='string'?detail:JSON.stringify(detail));}
 return response.json();
}
export const metricLabels:Record<string,string>={liabilities_to_assets:'资产负债率',interest_bearing_debt_to_assets:'有息负债率',quick_ratio:'速动比率'};
export function display(key:string,m:Metric){return m.value===null?'—':m.display_value||'—'}
export const errorLabels:Record<string,string>={fact_version_conflict:'事实版本已变化，请重新载入并核对后导入',authentication_required:'请先登录',invalid_credentials:'账号或密码不正确',login_rate_limited:'尝试次数过多，请五分钟后再试',project_membership_required:'你没有这个项目的访问权限',writer_required:'仅编制人员可以进行此操作',calculate_current_facts_first:'请先计算当前版本的财务指标',section_missing_or_stale:'请先生成当前版本的章节',section_version_conflict:'章节已被修改，请重新载入后再保存',section_stale:'资料已更新，请重新生成章节',model_data_not_authorized:'当前资料未授权发送至 Agnes，Markdown 已保留但不会调用模型',agnes_not_configured:'请先由管理员配置 Agnes 服务和服务器凭据',agnes_invalid_configuration:'Agnes 服务配置无效，请联系管理员检查',agnes_transport_error:'暂时无法连接 Agnes 服务，请稍后重试',agnes_rate_limited:'Agnes 服务请求繁忙，请稍后重试',agnes_context_budget_exceeded:'资料内容过长，无法在一次识别中处理',agnes_output_truncated:'Agnes 返回内容不完整，请重新识别',agnes_response_rejected:'Agnes 未返回可用的识别结果',agnes_invalid_json:'Agnes 返回格式无效，请重新识别',agnes_invalid_response:'Agnes 返回格式无效，请重新识别',agnes_response_too_large:'Agnes 返回内容过大，无法安全处理',agnes_retry_limit_exceeded:'识别重试次数已用完，请重新提交',stage_attempt_limit_exceeded:'识别重试次数已用完，请重新提交',stage_response_invalid:'Agnes 返回格式无效，请重新识别',stage_cache_invalid:'识别缓存校验失败，请重新提交',stage_call_failed:'识别服务调用失败，请稍后重试',stale_task_lease:'识别任务已由其他后台进程接管',invalid_evidence_locator_or_value:'事实值、原文或行号与原件不一致',source_hash_or_format_invalid:'来源摘要不匹配，或该格式尚未支持事实导入',unsafe_filename:'文件名包含非法路径',formal_publication_disabled_M1:'首轮只输出待复核稿',stale_task_input:'任务输入已变化，请基于当前版本重新生成',source_value_not_found:'该数字无法在来源 Markdown 中验证，不能直接确认',markdown_not_ready:'Markdown 尚未生成',unsupported_format:'暂不支持该文件格式',csrf_failed:'会话校验失败，请重新登录'};
export function friendly(message:string){return errorLabels[message]||message}

export const conceptLabels:Record<string,string>={total_assets:'资产总额',total_liabilities:'负债总额',interest_bearing_debt:'有息负债',current_assets:'流动资产',current_liabilities:'流动负债',inventory:'存货',revenue:'营业收入',cost:'营业成本'};
export function reasonLabel(reason:string|null){if(!reason)return '';if(reason.startsWith('missing_required_input:'))return '缺少'+(conceptLabels[reason.split(':')[1]]||'必要输入')+'数据';return ({zero_denominator:'分母为零，无法计算',entity_scope_period_unit_conflict:'主体、范围、期间或单位不一致',unresolved_fact_conflict:'事实候选存在冲突，需先核对'} as Record<string,string>)[reason]||reason}
